version: '3.8'
services:
  eventsourcing_mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: Logitar.EventSourcing_mssql
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: mWGEgJcrV5dzRyqb
    ports:
      - 1435:1433

  eventsourcing_postgres:
    image: postgres
    container_name: Logitar.EventSourcing_postgres
    environment:
      POSTGRES_PASSWORD: cptBg3hZ9qC6a5Vb
    ports:
      - 5435:5432
