version: '3.8'
name: event_sourcing
services:
  event_sourcing_mongo:
    image: mongo
    container_name: Logitar.EventSourcing_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: demo
      MONGO_INITDB_ROOT_PASSWORD: AwHE5MRKBeY9CsJu
    ports:
      - 27015:27017

  event_sourcing_mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: Logitar.EventSourcing_mssql
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: mWGEgJcrV5dzRyqb
    ports:
      - 1435:1433

  event_sourcing_postgres:
    image: postgres
    container_name: Logitar.EventSourcing_postgres
    environment:
      POSTGRES_PASSWORD: cptBg3hZ9qC6a5Vb
    ports:
      - 5435:5432
