name: event_sourcing
services:
  event_sourcing_kurrent:
    image: docker.eventstore.com/eventstore-preview/eventstoredb-ee:24.10.0-preview1-x64-8.0-bookworm-slim
    container_name: Logitar.EventSourcing_kurrent
    restart: unless-stopped
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_NODE_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - 2115:2113
    volumes:
      - type: volume
        source: eventstore-volume-data
        target: /var/lib/eventstore
      - type: volume
        source: eventstore-volume-logs
        target: /var/log/eventstore

  event_sourcing_mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: Logitar.EventSourcing_mssql
    restart: unless-stopped
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: mWGEgJcrV5dzRyqb
    ports:
      - 1435:1433

  event_sourcing_postgres:
    image: postgres
    container_name: Logitar.EventSourcing_postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: cptBg3hZ9qC6a5Vb
    ports:
      - 5435:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  eventstore-volume-data:
  eventstore-volume-logs:
  postgres_data:
